name: school_test_online
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts:
  flutter_screenutil:
  flutter_bloc:
  equatable:
  shared_preferences:
  font_awesome_flutter:
  flutter_cache_manager:
  dartz:
  dio:
  get_it:
  video_player:
  url_launcher:
  pdfx:
  intl:
  audioplayers: ^6.0.0
  image_picker:
  pusher_client_fixed:
  file_picker:
  flutter_local_notifications:
  flutter_sound: ^9.16.3
  permission_handler:
  flutter_pdfview:
  path_provider:
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lang/


